# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c37ec84d1f5c9c05aac5c43cb6fad9febc55596ddfcca8bc68a5995328ac78f58ba9684cdc66aaa1d557b4e3c921d1749e978f1456356464b2c67332d78921b1

test:
  secret_key_base: be89469f9fc0d2036fadcac21c199ec94a8b1043633ccc8b12b0b84c498df8acb5cbdd319ba506d480c8416c1c7a5224181f595703664e94bf8af6d3f52ac85e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
